"""initial

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("section", sa.String(length=8), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["skills.id"], name=op.f("fk_skills_parent_id_skills")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("test_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "exam_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("difficulty_setting", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=12), server_default="in_progress", nullable=False),
        sa.Column("rw_score", sa.SmallInteger(), nullable=True),
        sa.Column("math_score", sa.SmallInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_exam_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_sessions")),
    )
    op.create_index(op.f("ix_exam_sessions_user_id"), "exam_sessions", ["user_id"], unique=False)
    op.create_table(
        "official_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("taken_on", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("label", sa.String(length=100), server_default="", nullable=False),
        sa.Column("rw", sa.SmallInteger(), nullable=False),
        sa.Column("math", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint(
            "math BETWEEN 200 AND 800 AND math % 10 = 0", name=op.f("ck_official_scores_math_range")
        ),
        sa.CheckConstraint(
            "rw BETWEEN 200 AND 800 AND rw % 10 = 0", name=op.f("ck_official_scores_rw_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_official_scores_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_official_scores")),
    )
    op.create_index(op.f("ix_official_scores_user_id"), "official_scores", ["user_id"], unique=False)
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.String(length=64), nullable=False),
        sa.Column("format", sa.String(length=3), nullable=False),
        sa.Column("difficulty", sa.String(length=6), nullable=False),
        sa.Column("difficulty_rating", sa.Float(), nullable=False),
        sa.Column(
            "content",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=9), nullable=False),
        sa.Column("status", sa.String(length=11), server_default="active", nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("difficulty IN ('easy','medium','hard')", name=op.f("ck_questions_difficulty")),
        sa.CheckConstraint("format IN ('mc','spr')", name=op.f("ck_questions_format")),
        sa.CheckConstraint("source IN ('generator','llm','seed')", name=op.f("ck_questions_source")),
        sa.CheckConstraint("status IN ('active','quarantined')", name=op.f("ck_questions_status")),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], name=op.f("fk_questions_skill_id_skills")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_questions_content_hash")),
    )
    op.create_index("ix_questions_pick", "questions", ["skill_id", "difficulty", "status"], unique=False)
    op.create_table(
        "review_schedule",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.String(length=64), nullable=False),
        sa.Column("interval_days", sa.SmallInteger(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], name=op.f("fk_review_schedule_skill_id_skills")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_review_schedule_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "skill_id", name=op.f("pk_review_schedule")),
    )
    op.create_index(op.f("ix_review_schedule_due_at"), "review_schedule", ["due_at"], unique=False)
    op.create_table(
        "skill_mastery",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.String(length=64), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_practiced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], name=op.f("fk_skill_mastery_skill_id_skills")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_skill_mastery_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "skill_id", name=op.f("pk_skill_mastery")),
    )
    op.create_table(
        "study_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column(
            "plan",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_study_plans_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_plans")),
    )
    op.create_index(op.f("ix_study_plans_user_id"), "study_plans", ["user_id"], unique=False)
    op.create_table(
        "exam_modules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=4), nullable=False),
        sa.Column("stage", sa.SmallInteger(), nullable=False),
        sa.Column("route", sa.String(length=6), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["exam_sessions.id"],
            name=op.f("fk_exam_modules_session_id_exam_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_modules")),
        sa.UniqueConstraint("session_id", "section", "stage", name=op.f("uq_exam_modules_session_id")),
    )
    op.create_table(
        "question_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name=op.f("fk_question_reports_question_id_questions")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_question_reports_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_reports")),
    )
    op.create_index(
        op.f("ix_question_reports_question_id"), "question_reports", ["question_id"], unique=False
    )
    op.create_table(
        "exam_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("pretest", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["exam_modules.id"],
            name=op.f("fk_exam_items_module_id_exam_modules"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name=op.f("fk_exam_items_question_id_questions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_items")),
        sa.UniqueConstraint("module_id", "position", name=op.f("uq_exam_items_module_id")),
    )
    op.create_table(
        "responses",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("exam_item_id", sa.Integer(), nullable=True),
        sa.Column("answer", sa.String(length=16), nullable=True),
        sa.Column("correct", sa.Boolean(), nullable=True),
        sa.Column("time_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("flagged", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "eliminated",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("miss_reason", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("mode IN ('exam','drill','training')", name=op.f("ck_responses_mode")),
        sa.ForeignKeyConstraint(
            ["exam_item_id"],
            ["exam_items.id"],
            name=op.f("fk_responses_exam_item_id_exam_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name=op.f("fk_responses_question_id_questions")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_responses_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_responses")),
        sa.UniqueConstraint("exam_item_id", name=op.f("uq_responses_exam_item_id")),
    )
    op.create_index(op.f("ix_responses_question_id"), "responses", ["question_id"], unique=False)
    op.create_index("ix_responses_user_time", "responses", ["user_id", "created_at"], unique=False)
    op.create_table(
        "mastery_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.String(length=64), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("response_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["responses.id"],
            name=op.f("fk_mastery_history_response_id_responses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], name=op.f("fk_mastery_history_skill_id_skills")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_mastery_history_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mastery_history")),
    )
    op.create_index(
        "ix_mastery_history_user_skill",
        "mastery_history",
        ["user_id", "skill_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mastery_history_user_skill", table_name="mastery_history")
    op.drop_table("mastery_history")
    op.drop_index("ix_responses_user_time", table_name="responses")
    op.drop_index(op.f("ix_responses_question_id"), table_name="responses")
    op.drop_table("responses")
    op.drop_table("exam_items")
    op.drop_index(op.f("ix_question_reports_question_id"), table_name="question_reports")
    op.drop_table("question_reports")
    op.drop_table("exam_modules")
    op.drop_index(op.f("ix_study_plans_user_id"), table_name="study_plans")
    op.drop_table("study_plans")
    op.drop_table("skill_mastery")
    op.drop_index(op.f("ix_review_schedule_due_at"), table_name="review_schedule")
    op.drop_table("review_schedule")
    op.drop_index("ix_questions_pick", table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_official_scores_user_id"), table_name="official_scores")
    op.drop_table("official_scores")
    op.drop_index(op.f("ix_exam_sessions_user_id"), table_name="exam_sessions")
    op.drop_table("exam_sessions")
    op.drop_table("users")
    op.drop_table("skills")
    # ### end Alembic commands ###
